logging:
  level:
    root: INFO
spring:
  cloud:
    discovery:
      enabled: true
    config:
      fail-fast: true
  retry:
    max-attempts: 10            # Retry up to 5 times
    initial-interval: 1000      # Start with 1 second delay (1000 ms)
    multiplier: 2               # Multiply the delay by 2 each time
    max-interval: 5000          # Maximum delay between retries is 5 seconds
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:9999/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
common-params:
  base-url: ${BASE_URL:http://localhost:8080}
