spring:
  cloud:
    discovery:
      enabled: true
    config:
      fail-fast: true
  retry:
    max-attempts: 10            # Retry up to 5 times
    initial-interval: 1000      # Start with 1 second delay (1000 ms)
    multiplier: 2               # Multiply the delay by 2 each time
    max-interval: 5000          # Maximum delay between retries is 5 seconds
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USER_NAME:test@gmail.com}
    password: ${MAIL_PASSWORD:xxxx xxxx xxxx xxxx}
    properties:
      "[mail.smtp.auth]": true
      "[mail.smtp.starttls.enable]": true
      "[mail.smtp.connectiontimeout]": 5000
      "[mail.smtp.timeout]": 3000
      "[mail.smtp.writetimeout]": 5000
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:9999/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
common-params:
  base-url: ${BASE_URL:http://localhost:8080}
  front-base-url: ${FRONT_BASE_URL:http://localhost:3000}

logging:
  level:
    root: INFO
  sensitive:
    exact-redacted-keys:
      - authorization
      - cookie
      - set-cookie
      - x-api-key
      - proxy-authorization
      - x-forwarded-for
      - password
      - passwd
      - ssn
      - secret
      - token
      - key
      - creditcard
      - ccnumber
      - iban
    pattern-redacted-keys:
      - "(?i).*token.*"
      - "(?i).*secret.*"
    pattern-redacted-values:
      - "\\b\\d{3}-\\d{2}-\\d{4}\\b"  #SSNs
      - "[A-Z]{2}[0-9]{2}[A-Z0-9]{11,30}" #IBANs
      - "(?i)password:.*"

debug-mode: false