server:
  port: 4000
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/user_service
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
            authorization-grant-type: authorization_code
            redirect-uri: ${GOOGLE_REDIRECT_HOST:http://localhost:8080}/login/oauth2/code/{registrationId}
            provider: google
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: read:user, user:email
            authorization-grant-type: authorization_code
            redirect-uri: ${GITHUB_REDIRECT_HOST:http://localhost:8080}/login/oauth2/code/{registrationId}

            provider: github
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
logging:
  level:
    org:
      springframework:
        security: TRACE
security:
  whitelisted-endpoints:
    - /login
    - /logout
    - /register
    - /authenticate
    - /refresh-token
    - /login/oauth2/code/**
    - /oauth2/authorization/**
  encryption:
    aes-key: ${AES_ENCRYPTION_KEY:32-characters-long-plaintext-key}
  jwt:
    secret: ${JWT_SECRET:secret12345667890qwertyuiopasdfghjkl}
    refreshTokenExpiration:  ${JWT_REFRESH_TOKEN_EXPIRATION:180000}
    accessTokenExpiration: ${JWT_ACCESS_TOKEN_EXPIRATION:30000}
  auth:
    redirect:
      success-url: ${AUTH_SUCCESS_REDIRECT:http://localhost:3000/auth-success}
      failure-url: ${AUTH_FAILURE_REDIRECT:http://localhost:3000/login}
  verification-token:
    expiration: ${VERIFICATION_TOKEN_EXPIRATION:3}
